<a href="https://colab.research.google.com/github/arun-arunisto/PyTorch/blob/main/Tutorial_1_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data. Tensors are also optimized for automatic differentiation.

In [1]:
import torch
import numpy as np

## Initailizing a Tensor

Tensor can intialize in different ways:

1. Directly from data

In [2]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
tensor_data = torch.tensor(data)

In [7]:
print("Normal data:\n",data)

Normal data:
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [8]:
print("Tensor data:\n",tensor_data)

Tensor data:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


2. From a **Numpy** array

In [5]:
np_array = np.array(data)
tensor_np = torch.from_numpy(np_array)

In [6]:
print("Numpy array:\n",np_array)

Numpy array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print("Tensor numpy array:\n",tensor_np)

Tensor numpy array:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


3. From another tensor

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [10]:
# retaining the properties of tensor data
tensor_ones = torch.ones_like(tensor_data)

In [11]:
print("Tensor data used for retaining:\n",tensor_data)

Tensor data used for retaining:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [12]:
print("Retained data:\n",tensor_ones)

Retained data:
 tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [13]:
# overrides the shape and retaining the properties of the tensor
tensor_rand = torch.rand_like(tensor_np, dtype=torch.float)

In [15]:
print("Overrides shape with random values:\n",tensor_rand)

Overrides shape with random values:
 tensor([[0.7089, 0.5365, 0.4397],
        [0.2067, 0.0933, 0.6247],
        [0.6613, 0.8169, 0.5444]])


4. With random or constant values

In [16]:
shape = (2, 3,)

In [17]:
#with random tensor
random_tensor = torch.rand(shape)

In [18]:
print("Random tensor:\n",random_tensor)

Random tensor:
 tensor([[0.6979, 0.0677, 0.6600],
        [0.2520, 0.1995, 0.9161]])


`shape` is a tuple of tensor dimensions.

In [19]:
#with ones
ones_tensor = torch.ones(shape)

In [20]:
print("Ones tensor:\n",ones_tensor)

Ones tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [21]:
#with zeros
zeros_tensor = torch.zeros(shape)

In [22]:
print("Zeros tensor:\n",zeros_tensor)

Zeros tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [23]:
tensor_ = torch.rand(2, 3)

In [24]:
print("Shape of the tensor:\n",tensor_.shape)

Shape of the tensor:
 torch.Size([2, 3])


In [25]:
print("Datatype of the tensor:\n",tensor_.dtype)

Datatype of the tensor:
 torch.float32


In [26]:
print("Device where the tensor is stored:\n",tensor_.device)

Device where the tensor is stored:
 cpu


## Operations on tensor

Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more.

Each of these operations can be run on the GPU (at typically higher speeds than on a CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [27]:
#checking for gpu (i didnt change my runtime to gpu so it will be cpu only)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Using {} device'.format(device))

Using cpu device


In [28]:
# moving our tensor to device(GPU or CPU based on availability)
tensor_ = tensor_.to(device)

***Standard indexing and slicing***

In [29]:
tensor_ops = torch.ones(4, 4)

In [30]:
print("Tensor data:\n",tensor_ops)

Tensor data:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [31]:
print("First row:\n",tensor_ops[0])

First row:
 tensor([1., 1., 1., 1.])


In [32]:
print("First column:\n",tensor_ops[:, 0])

First column:
 tensor([1., 1., 1., 1.])


In [33]:
print("Last column:\n",tensor_ops[..., -1])

Last column:
 tensor([1., 1., 1., 1.])


In [34]:
#changing values
tensor_ops[:, 1] = 0

In [35]:
print("After changing 1 to 0:\n",tensor_ops)

After changing 1 to 0:
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


***Concatenating tenosrs***

You can use `torch.cat` to concatenate a sequence of tensors along a given dimension.

In [39]:
tensor_concat = torch.cat([tensor_ops, tensor_ops, tensor_ops], dim=1)

In [40]:
print("After concatenating:\n",tensor_concat)

After concatenating:
 tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


`torch.cat()` concatenates the given sequence along an existing dimension. There's an another method `torch.stack()` another tensor joining op that is subtly different from torch.cat.

`torch.stack()` - Concatenates a sequence of tensors along a new dimension and  all tensors need to be of the same size.

In [41]:
x = torch.randn(2, 3)
print("Random tensor x:\n",x)

Random tensor x:
 tensor([[-2.5896,  0.4358, -0.6318],
        [ 0.6066,  0.2952,  0.2113]])


In [42]:
#dim=0
dim_0_tensor = torch.stack((x, x)) #same as torch.stack((x, x), dim=0)

In [43]:
print("Dimesion 0:\n",dim_0_tensor)

Dimesion 0:
 tensor([[[-2.5896,  0.4358, -0.6318],
         [ 0.6066,  0.2952,  0.2113]],

        [[-2.5896,  0.4358, -0.6318],
         [ 0.6066,  0.2952,  0.2113]]])


In [46]:
print("Shape of the tensor:\n",dim_0_tensor.size())

Shape of the tensor:
 torch.Size([2, 2, 3])


In [44]:
#dim=1
dim_1_tensor = torch.stack((x, x), dim=1)

In [47]:
print("Dimension 1:\n",dim_1_tensor)

Dimension 1:
 tensor([[[-2.5896,  0.4358, -0.6318],
         [-2.5896,  0.4358, -0.6318]],

        [[ 0.6066,  0.2952,  0.2113],
         [ 0.6066,  0.2952,  0.2113]]])


In [48]:
print("Shape of the tensor:\n",dim_1_tensor.size())

Shape of the tensor:
 torch.Size([2, 2, 3])


In [49]:
#dim=2
dim_2_tensor = torch.stack((x, x), dim=2)

In [50]:
print("Dimension 2:\n",dim_2_tensor)

Dimension 2:
 tensor([[[-2.5896, -2.5896],
         [ 0.4358,  0.4358],
         [-0.6318, -0.6318]],

        [[ 0.6066,  0.6066],
         [ 0.2952,  0.2952],
         [ 0.2113,  0.2113]]])


In [51]:
print("Shape of the tensor:\n",dim_2_tensor.size())

Shape of the tensor:
 torch.Size([2, 3, 2])


In [52]:
#dim=-1
dim_neg_1_tensor = torch.stack((x, x), dim=-1)

In [53]:
print("Dimesion -1:\n",dim_neg_1_tensor)

Dimesion -1:
 tensor([[[-2.5896, -2.5896],
         [ 0.4358,  0.4358],
         [-0.6318, -0.6318]],

        [[ 0.6066,  0.6066],
         [ 0.2952,  0.2952],
         [ 0.2113,  0.2113]]])


In [54]:
print("Shape of the tensor:\n",dim_neg_1_tensor.size())

Shape of the tensor:
 torch.Size([2, 3, 2])


## Arithematic Operations
Matrix Multiplication between two two tensors

In [57]:
#first method
y1 = tensor_ @ tensor_.T

In [58]:
print("1st method:\n",y1)

1st method:
 tensor([[1.6309, 1.6063],
        [1.6063, 2.0564]])


In [59]:
#second method
y2 = tensor_.matmul(tensor_.T)

In [60]:
print("2nd method:\n",y2)

2nd method:
 tensor([[1.6309, 1.6063],
        [1.6063, 2.0564]])


Computing element wise product

In [61]:
#first method
z1 = tensor_ * tensor_

In [62]:
print("First method:\n",z1)

First method:
 tensor([[0.5656, 0.0771, 0.9883],
        [0.8217, 0.7643, 0.4704]])


In [63]:
#second method
z2 = tensor_.mul(tensor_)

In [64]:
print("Second method:\n",z2)

Second method:
 tensor([[0.5656, 0.0771, 0.9883],
        [0.8217, 0.7643, 0.4704]])


If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using `item()`:

In [65]:
agg = tensor_.sum()
agg_item = agg.item()

In [66]:
print("Value:\n",agg_item)

Value:
 4.4903788566589355


In [67]:
print("Type of the value:\n",type(agg_item))

Type of the value:
 <class 'float'>


Operations that store the result into the operand are called in-place. They are denoted by a `_` suffix. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [68]:
print("Tensor before:\n",tensor_)

Tensor before:
 tensor([[0.7521, 0.2776, 0.9941],
        [0.9065, 0.8742, 0.6859]])


In [69]:
tensor_.add_(5)

tensor([[5.7521, 5.2776, 5.9941],
        [5.9065, 5.8742, 5.6859]])

In [70]:
print("Tensor after:\n",tensor_)

Tensor after:
 tensor([[5.7521, 5.2776, 5.9941],
        [5.9065, 5.8742, 5.6859]])


## Bridge with numpy

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

In [71]:
tens_ones = torch.ones(5)
num_ones = tens_ones.numpy()

In [72]:
print("Tensor:\n",tens_ones)

Tensor:
 tensor([1., 1., 1., 1., 1.])


In [73]:
print("Numpy:\n",num_ones)

Numpy:
 [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

In [74]:
tens_ones.add_(1)

tensor([2., 2., 2., 2., 2.])

In [75]:
num_ones

array([2., 2., 2., 2., 2.], dtype=float32)

## Numpy array to tensor

In [76]:
numpy_arr = np.ones(5)
tensor_arr = torch.from_numpy(numpy_arr)

In [77]:
print("Numpy array:\n",numpy_arr)

Numpy array:
 [1. 1. 1. 1. 1.]


In [78]:
print("Tensor array:\n",tensor_arr)

Tensor array:
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


Changes in the NumPy array reflects in the tensor.

In [79]:
np.add(numpy_arr, 1, out=numpy_arr)

array([2., 2., 2., 2., 2.])

In [80]:
tensor_arr

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)